### PR TITLE
WW14 release misc changes

### PR DESCRIPTION
**Pull request by clsulliv**

### CODE REVIEW

**Review by jialeif — APPROVED** [review]
LGTM.
https://github.com/intel/tdx-tools/pull/49 fixes the build failure. The check for pkg-build fails because this PR not rebased on the fix.
For rhel guest image we can try to download it directly later, since it already has efi partition.
However, I'd prefer to get this PR merged firstly.

**Comment by clsulliv** [comment]
There are still a few things incomplete here:

- [ ] build-repo.sh needs updated for the new package(s)
- [ ] need to clean up deprecated packages
- [ ] need to update the qemu package (when we can)

**Comment by jialeif** [comment]
@kenplusplus do you agree
1. we get this PR merged
2. remove intel-mvp-tdx-host-kernel, intel-mvp-tdx-qemu-kvm, intel-mvp-tdx-guest-kernel
3. add build tool for spr-qemu

**Comment by clsulliv** [comment]
build-repo.sh has been updated. It needed some changes to account for the SPR kernel package building both host and guest. Please check it.

Still need to decide what to do with the QEMU package.

**Comment by clsulliv** [comment]
Added the spr-qemu build. Note: source code is not yet added to the public repo, so the build will fail until that is available.

I also updated the build-repo.sh scripts and workflows to match the new packages.

**Review by jialeif — APPROVED** [review]
LGTM
Thanks!

**Pull request merged**
