### PR TITLE
build/ubuntu-22.04/guest-image/: Need to startup the NTP (Network Time Protocol) service configuration for both TD and legacy VM

### PR DESCRIPTION
**Pull request by zhlsunshine**
It's necessary to set the Real-Time Clock configuration for both TD and legacy VM.
There may be some problems, such as the certificates expiration for k8s node certificate and some workloads based on specification VM images, for k8s cluster if RTC configuration is not set. 

**Problem description:** 
When launching a virtual machine (VM), the VM date is typically determined by the host operating system or the underlying hypervisor.
So I encountered the cases many times,  below is the step list for this problem:

1. I launch a VM and install the k8s cluster, and the time of the VM is inaccurate. 
2. I deploy some workloads with certificates expiration error
3. I set the corrected VM date via `date -s "YYYY-MM-DD HH:MM:SS"`
4. The node certificates expiration error can be seen due to it shows that the whole cluster has been created 3-4 month ago even it has been created 1-2 days ago in real.

**Fix solution:**

reference the comment here: https://github.com/intel/tdx-tools/pull/369#issuecomment-1617886040

### CODE REVIEW

**Comment by kenplusplus** [comment]
all host's RTC or clock could not be trusted due to confidential computing's purpose. The only approach to get accurate date is via NTP network clock. Have you configure the correct NTP clock within your VM?

**Comment by zhlsunshine** [comment]
> all host's RTC or clock could not be trusted due to confidential computing's purpose. The only approach to get accurate date is via NTP network clock. Have you configure the correct NTP clock within your VM?

Hi @kenplusplus, thanks for your comment and u r correct, it should not be trusted. I have not configure the correct NTP clock in the TDVM. BTW, if so should I make the NTP get ready in the tdx image?

**Comment by zhlsunshine** [comment]
One more thing, @kenplusplus ,  I noticed that the clock setting in `utils/pycloudstack/pycloudstack/templates/sgx-base.xml` is different with others. is it required? Thanks!

**Comment by kenplusplus** [comment]
> > all host's RTC or clock could not be trusted due to confidential computing's purpose. The only approach to get accurate date is via NTP network clock. Have you configure the correct NTP clock within your VM?
> 
> Hi @kenplusplus, thanks for your comment and u r correct, it should not be trusted. I have not configure the correct NTP clock in the TDVM. BTW, if so should I make the NTP get ready in the tdx image?

Yes, you can use package like ntp or chony. By default it will use official NTP server, you can change to internal NTP server if behind the proxy.

**Comment by zhlsunshine** [comment]
Hi @kenplusplus, could you please help to review the new submit? Thanks!

**Comment by kenplusplus** [comment]
> Hi @kenplusplus, could you please help to review the new submit? Thanks!

Thanks, since now we are using cloud-init as official configuration tool, you only need add one line code to fix this issue 

https://github.com/intel/tdx-tools/blob/ea0a9d0b53d6225e10bd97e401b3114d78c9c837/build/ubuntu-22.04/guest-image/cloud-init-data/user-data.template#L29

  - golang
  - golang-doc
  - ntp  <== only need add one line code here

**Review by kenplusplus — APPROVED** [review]
LGTM

**Pull request merged**
