### PR TITLE
tests: minor adjustment for environment settings

### PR DESCRIPTION
**Pull request by intelzhongjie**

### CODE REVIEW

**Comment by intelzhongjie** [comment]
The module "py" is needed on some Ubuntu host. Otherwise, we will get some error as below when we run the test:
ModuleNotFoundError: No module named 'py.xml'; 'py' is not a package

**Comment by kenplusplus** [comment]
> No module named 'py.xml'; 'py' is not a package

why? isn't the build happend in virtual env?

**Comment by intelzhongjie** [comment]
> > No module named 'py.xml'; 'py' is not a package
> 
> why? isn't the build happend in virtual env?

The reason is the pytest version on Ubuntu currently is newer that includes some change remove the implicit dependency of "py" (details can be found from here https://github.com/pytest-dev/pytest/issues/10428 and the related issues mentioned in that)

Regarding to the license check issue, it needs this for license check: https://github.com/intel/tdx-tools/pull/422/files

**Comment by intelzhongjie** [comment]
So please review https://github.com/intel/tdx-tools/pull/422 before this. Thanks!

**Review by kenplusplus — APPROVED** [review]
LGTM

**Pull request merged**
