### PR TITLE
Add user guide for IMA usage with TDX RTMR

### PR DESCRIPTION
**Pull request by Ruoyu-y**
add a user guide to give brief introduction and detail configurations for IMA usage with RTMR.

### CODE REVIEW

**Comment by Ruoyu-y** [comment]
@ruomengh Here's the user guide for IMA usage

**Comment by kenplusplus** [comment]
Hi Ruomeng, there are lots document checking error. Could you please update the allow dict file? Or if want to bypass the spelling check , you can use  \`code\` , the content within \` will not be checked.

**Comment by ruomengh** [comment]
> Hi Ruomeng, there are lots document checking error. Could you please update the allow dict file? Or if want to bypass the spelling check , you can use `code` , the content within ` will not be checked.

@Ruoyu-y Could you please fix scan error as Ken suggests?

**Comment by Ruoyu-y** [comment]
> > Hi Ruomeng, there are lots document checking error. Could you please update the allow dict file? Or if want to bypass the spelling check , you can use `code` , the content within ` will not be checked.
> 
> @Ruoyu-y Could you please fix scan error as Ken suggests?

Sure. Let me update the allow dict file. And i accidentially close the PR while rebasing the change. Let me create another PR for these changs.

**Pull request closed without merging**
