### PR TITLE
tests: minor adjustments

### PR DESCRIPTION
**Pull request by intelzhongjie**
1. Update dependency. Add py into and update pyyaml.
2. Set "ubuntu" as default in run.sh.
3. Adjust timeout for test_tdvm_lifecycle.py.
4. Remove shstk for some cases (e.g. test_tdvm_tsc.py).
5. Add README to clarify some dependencies.
6. Remove test_max_cpu.py.

### CODE REVIEW

**Comment by intelzhongjie** [comment]
pyyaml need to update to 6.0 according to https://github.com/yaml/pyyaml/issues/724 . Otherwise, it will fail when we run "source setupenv.sh".

**Comment by intelzhongjie** [comment]
test_max_cpu.py is not well supported by some distribution. So just remove it for now.

**Comment by intelzhongjie** [comment]
> Could you please refine the format of tests/README.md with a regular markdown structure? Also clarity how to get base guest image.

Updated. Please review the latest version.

**Review by ruomengh — APPROVED** [review]
LGTM

**Pull request merged**
