### PR TITLE
deploy: initiate the ansible deploy tool for TDX packages installation

### PR DESCRIPTION
**Pull request by kenplusplus**

### CODE REVIEW

**Review by jialeif — APPROVED** [review]
LGTM.
Will create ubuntu repo later instead of local install.

**Comment by kenplusplus** [comment]
> I ran into a few issues with this. For one I don't use tdxdev as a username so I had to create that on both the ansible machine and target machine. The procedure I followed is to get the latest version of main, build all of the files that are in guest_repo, and then run ` ./docker-playbook.sh -i config-ansible/hosts tdx_stack/tdx_host_install.yml` It gets to the step where it tries to install the .deb files but it fails with "Some packages could not be installed. This may mean that you have requested an impossible situation." If I run the command myself I see the same errors. This package seems to be the culprit.
> 
> The following packages have unmet dependencies: shim-signed : Depends: grub-efi-amd64-signed (>= 1.187.2~) but it is not going to be installed or grub-efi-arm64-signed (>= 1.187.2~) but it is not installable E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
> 
> When I setup TDX before I used the 5.19 branch or tag. I was not doing it off of main so something else might have come up.

It looks weird, for TDX host, it should not install shim or grub. are you really copy the debian package for TDX host instead of TDX guest?

**Comment by eadamsintel** [comment]
I was just sending you an email on this. I had confused the guest_repo directory with the host_repo.  I think if you renamed "tdx_repo" to "tdx_host_repo" it would help new users like myself avoid making this mistake.

**Comment by kenplusplus** [comment]
> I was just sending you an email on this. I had confused the guest_repo directory with the host_repo. I think if you renamed "tdx_repo" to "tdx_host_repo" it would help new users like myself avoid making this mistake.

The problem is that the content for tdx_repo could be host or guest. I am trying to make this deployment tool working for both host and guest. Now it only supports host.

**Comment by eadamsintel** [comment]
That makes sense.  I did not realize you were trying to make it work for guest as well.

**Pull request merged**
