### PR TITLE
Use "-shstk" to disable CET when booting TD guest

### PR DESCRIPTION
**Pull request by ruomengh**
To avoid TD guest boot failure, it needs to append "-shstk" in qemu command line to disable CET explicitly.

### CODE REVIEW

**Review by kenplusplus — APPROVED** [review]
LGTM

**Comment by clsulliv** [comment]
@ruomengh @kenplusplus I don't recall exactly when, but at some point the CET issue was fixed making `-shstk` no longer necessary.

In local testing I am able to boot a TD without the setting with no issue.

**Review by clsulliv — CHANGES_REQUESTED** [review]
Sorry, I did not check the actual commit before approving. Could you please update the commit message to follow CONTRIBUTING.md?

**Comment by ruomengh** [comment]
@clsulliv Thanks for the comment. I modified the commit message. Would you please review again?

**Pull request merged**
