### PR TITLE
Doc: Change links to relative link

### PR DESCRIPTION
**Pull request by Ruoyu-y**
* Change all links point to local to relative links
* Fix minor typos

### CODE REVIEW

**Review by kenplusplus — APPROVED** [review]
Original we need since TDX document generation tool depends on it, but now tdx DOCS already cleaned up. @ruomengh how do you think?

**Comment by Ruoyu-y** [comment]
If the docs are still needed, then there is one thing for this developer_guide.md. Currently the doc is based on kernel v5.15, do we need to change all the steps to be compatible with kernel v5.19?

**Comment by ruomengh** [comment]
> Original we need since TDX document generation tool depends on it, but now tdx DOCS already cleaned up. @ruomengh how do you think?

I think the link with release tag should not hardcode in the document for main branch. And yes, TDX docs don't refer to here anymore. So the changes look good to me.

**Comment by Ruoyu-y** [comment]
> If the docs are still needed, then there is one thing for this developer_guide.md. Currently the doc is based on kernel v5.15, do we need to change all the steps to be compatible with kernel v5.19?

@ruomengh any comments on this one?

**Comment by ruomengh** [comment]
> If the docs are still needed, then there is one thing for this developer_guide.md. Currently the doc is based on kernel v5.15, do we need to change all the steps to be compatible with kernel v5.19?

Main branch is always for the latest tdx kernel version that has been released, which means it should be for kernel 5.19 for the time being. Developer guide should update for kernel 5.19.  Could you please make sure the changes are valid for kernel 5.19.

**Comment by Ruoyu-y** [comment]
> > If the docs are still needed, then there is one thing for this developer_guide.md. Currently the doc is based on kernel v5.15, do we need to change all the steps to be compatible with kernel v5.19?
> 
> Main branch is always for the latest tdx kernel version that has been released, which means it should be for kernel 5.19 for the time being. Developer guide should update for kernel 5.19. Could you please make sure the changes are valid for kernel 5.19.

Got it. Then update needed for the patch.

**Review by kenplusplus — APPROVED** [review]
LGTM

**Pull request merged**
