### PR TITLE
remove .sh extension from setup.py for tdx_eventlog, tdx_tdreport, tdx_verify_rtmr

### PR DESCRIPTION
**Pull request by vli11**
add file entension to tdx_eventlogs, tdx_tdreport, tdx_verify_rtmr

### CODE REVIEW

**Comment by clsulliv** [comment]
It looks like the `git add` for the files with extensions was missed!

**Comment by clsulliv** [comment]
@vli11 Sorry, forgot to tag you. Please see above.

**Comment by vli11** [comment]
@clsulliv I noticed it will kick off shellcheck on the files if I add .sh extension, and that failed the shellcheck. so this time I remove the .sh from setup.sh instead, this corrects the error as well.

**Comment by kenplusplus** [comment]
LGTM

**Pull request merged**
